apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://https://github.com/yarelm/env-k8s.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://34.123.98.12
    namespace: default